services:
  postgres:
    image: postgres:15
    container_name: person_management_db
    environment:
      POSTGRES_DB: person_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sqlScript.sql:/docker-entrypoint-initdb.d/01-init.sql
    restart: unless-stopped

volumes:
  postgres_data:
